# Generated by Django 3.0.7 on 2020-08-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='your_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
