# Generated by Django 3.0.7 on 2020-08-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial_app', '0002_auto_20200803_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='your_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
